SDK liquidity guides
balancer/docs pull request #1
Opened 2023-02-02 17:27 UTC by gmbronco

Guides on how to use SDK to join / exit including swap + join / exits for boosted pools.
It makes "Liquidity Provisioning" obsolete, safe to remove, or I'm missing some details that would be helpful?

Swap join / exits are still quite awkward, because they aren't abstracted that well yet and need low level functions to build the calls.

2023-02-02 20:30 UTC, mikemcdonald requested changes

2023-02-02 20:30 UTC, mikemcdonald commented on docs/sdk/liquidity-managment/exit-pool.md
> +Exiting a Balancer pool is done by sending Balancer pool tokens (BPT) to the pool. In exchange, you receive the underlying tokens that make up the pool. For example, if the pool is stETH, composed of
Avoid using language like "sending BPT to the vault/pool" even if it's meant in a general sense. Users may take that literally and try an ERC20 transfer of the BPT which will then be lost

2023-02-02 20:30 UTC, mikemcdonald commented on docs/sdk/liquidity-managment/exit-pool.md
> +const pool = balancer.pools.find(poolId)
Maybe a hint or external link somewhere here that explains what the pool class is in the sdk.

2023-02-02 20:30 UTC, mikemcdonald commented on docs/sdk/liquidity-managment/exit-pool.md
> +const { to, data } = pool.buildExitExactBPTIn(
Add a natspec comment above `buildExitExactBPTin()` that describes each input. It's still not clear at first glance how the exiting to all tokens vs 1 token is different

2023-02-02 20:30 UTC, mikemcdonald commented on docs/sdk/liquidity-managment/exit-pool.md
> +
This snippet could use a few more code comments to explain things.

Ex: `.toChainedReference('1')`

2023-02-02 20:30 UTC, mikemcdonald commented on docs/sdk/liquidity-managment/exit-pool.md
> +  poolKind: 0, // 0 =  only Weighted Pool is supported
Assuming this is an Enum here? If so lets use that

2023-02-02 20:30 UTC, mikemcdonald commented on docs/sdk/liquidity-managment/exit-pool.md
> +    userData: defaultAbiCoder.encode(
Does it make sense to use the sdk userdata encoding helper here? Instead of the raw encode with ethers

2023-02-02 20:30 UTC, mikemcdonald commented on docs/sdk/liquidity-managment/exit-pool.md
> +      amount: '0',
A tip or comment about how a `0` amount means the vault batchswap use the previous step's output would be helpful

2023-02-02 20:30 UTC, mikemcdonald commented on docs/sdk/liquidity-managment/exit-pool.md
> +  limits: [MaxInt256, '0', '0'], // +ve for max to send, -ve for min to receive
What does the `ve` in the comments mean?

2023-02-02 20:30 UTC, mikemcdonald commented on docs/sdk/liquidity-managment/join-pool.md
> +Under the hood joining a pool is about sending your ERC20 tokens to the Vault where they are used as liquidity. In exchange for providing liquidity you will receive another ERC20 tokens representing
Same comment as previous about `sending` language

2023-02-02 20:30 UTC, mikemcdonald commented on docs/sdk/liquidity-managment/join-pool.md
> +It's important to note that you can set a limit on the amount of tokens you approve for the contract to access. For example, if you own 100 tokens and only want to invest 50 of them in the pool, you
Normally I like to error on the side of providing more context/info, but imo this comment section can be removed. I think its safe to assume any dev knows what token approvals are and tradeoffs between unlimited

2023-02-02 20:30 UTC, mikemcdonald commented on docs/sdk/liquidity-managment/join-pool.md
> +Setting `slippage`, also called "limits", is a way to protect yourself from potential losses when joining a pool. It means setting a minimum BPTs that you expect to receive when you join the pool. Th
Remove the last sentence. Too much nuance is needed to explain about setting a limit at 0

2023-02-02 20:30 UTC, mikemcdonald commented on docs/sdk/liquidity-managment/join-pool.md
> +>This method is particularly useful for joining pools with high relative liquidity, as it helps to minimize the potential for slippage, which can occur when join is changing token balances and at the
Can you clarify this hint? Not sure what is meant by `high relative liquidity`

2023-02-02 20:30 UTC, mikemcdonald commented on docs/sdk/liquidity-managment/join-pool.md
> +// Get optimal join amounts relative to `token`
Elaborate a little more here in the comment. Ex: out of the tokens in the pool, you pick one and set an amount. The helper will calculate the proportional amounts for the remaining tokens in the pool

2023-02-02 20:30 UTC, mikemcdonald commented on docs/sdk/liquidity-managment/join-pool.md
> +const impactPercentage = (100 * priceImpact / 1e18).toFixed(2)
We can keep this for now. But in general across all of our codebases doing any sort of `wad` scale math without using integers or bignumber is a bad practice

2023-02-03 14:29 UTC, gmbronco commented on docs/sdk/liquidity-managment/exit-pool.md
> +const pool = balancer.pools.find(poolId)
I added a reference to the type, but I am struggling with it a bit. The original idea was to fetch pool data from the subgraph and wrap it in a Pool model with methods. However, as the underlying data changes, it is easy to end up with models that are acting on outdated state. Additionally, the find method fetches all pools under the hood and caches them. This was meant to make working with SOR and APRs easier, but it makes single pool interactions unnecessarily slow and bloated.

We are planning to decouple data fetching and expose functional services so that you can use only what you need without forced data fetching. This is just a note for my own reference to revise these docs after refactoring is completed.

2023-02-03 14:32 UTC, gmbronco commented on docs/sdk/liquidity-managment/exit-pool.md
> +  poolKind: 0, // 0 =  only Weighted Pool is supported
Actually it's not a full poolType from TS. It's a Relayer enum and it's defined with one value only, so it's a hardcoded 0. Adding this link to the doc as well https://github.com/balancer-labs/balancer-v2-monorepo/blob/master/pkg/standalone-utils/contracts/relayer/VaultActions.sol/#L105

2023-02-03 14:33 UTC, gmbronco commented on docs/sdk/liquidity-managment/exit-pool.md
> +    userData: defaultAbiCoder.encode(
yes, updated.

2023-02-03 14:33 UTC, gmbronco commented on docs/sdk/liquidity-managment/exit-pool.md
> +  limits: [MaxInt256, '0', '0'], // +ve for max to send, -ve for min to receive
not sure, copied it from somewhere. changed them to +/- amounts

2023-02-03 14:35 UTC, gmbronco commented on docs/sdk/liquidity-managment/join-pool.md
> +It's important to note that you can set a limit on the amount of tokens you approve for the contract to access. For example, if you own 100 tokens and only want to invest 50 of them in the pool, you
agree, removed. was thinking more in a beginners context, but for that it can be explained in some other tutorial.

2023-02-03 14:37 UTC, gmbronco commented on docs/sdk/liquidity-managment/join-pool.md
> +>This method is particularly useful for joining pools with high relative liquidity, as it helps to minimize the potential for slippage, which can occur when join is changing token balances and at the
tried my best, does it need another edit?

`This method is particularly useful for providing relatively high liquidity compared to the current pool's liquidity. It helps to minimize the slippage, which occurs when join is changing individual token balances and at the same time their prices.`

2023-02-03 14:39 UTC, gmbronco commented on docs/sdk/liquidity-managment/join-pool.md
> +// Get optimal join amounts relative to `token`
i'll steal it

2023-02-03 14:39 UTC, gmbronco commented on docs/sdk/liquidity-managment/join-pool.md
> +const impactPercentage = (100 * priceImpact / 1e18).toFixed(2)
very good point, updated

2023-02-03 16:00 UTC, mikemcdonald commented on docs/sdk/liquidity-managment/join-pool.md
> +>This method is particularly useful for joining pools with high relative liquidity, as it helps to minimize the potential for slippage, which can occur when join is changing token balances and at the
Much clearer, thanks

2023-02-03 16:00 UTC, mikemcdonald approved these changes

2023-02-03 16:00 UTC, merged