Docs for Linear Pool Subgraph Integrations
balancer/docs pull request #79
Opened 2023-05-18 21:20 UTC by baileyspraggins

Adds documentation for updating the subgraph with new linear pool deployments

2023-05-19 14:57 UTC, gerrrg requested changes
Minor language edits and capitalizations

2023-05-19 14:57 UTC, gerrrg commented on docs/guides/boosted-pool-creators/new-protocol.md
> +In the `abi` folder add two JSON files. One containing the new linear pool factory's abi and the next containing the new linear pool's abi.
```suggestion
In the `abi` folder, add two JSON files: one for the new Linear Pool ABI and one for the corresponding factory ABI.
```

2023-05-19 14:57 UTC, gerrrg commented on docs/guides/boosted-pool-creators/new-protocol.md
> +Adding new integrations to the subgraph is important for tracking linear pool creations. The subgraph is maintained in the [Balancer Subgraph Repository](https://github.com/balancer/balancer-subgraph
```suggestion
Adding new integrations to the subgraph is important for tracking Linear Pool creations. The subgraph is maintained in the [Balancer Subgraph Repository](https://github.com/balancer/balancer-subgraph-v2). 
```

2023-05-19 14:57 UTC, gerrrg commented on docs/guides/boosted-pool-creators/new-protocol.md
> +Open the `networks.yaml` file and add an entry for each network that the new linear pool is deployed on. This includes information on the `network`, factory name, `address` of the deployed contract,
```suggestion
In `networks.yaml`, add an entry for each network that the new Linear Pool is deployed on. This includes information on the `network`, factory name, `address` of the deployed contract, and `startBlock`. Maintain the current naming conventions by naming the factory, `<protocol>LinearPool<version>Factory`. 
```

2023-05-19 14:57 UTC, gerrrg commented on docs/guides/boosted-pool-creators/new-protocol.md
> +Add the linear pool to the `PoolType` namespaces within `src/mappings/helpers/pool.ts`. In the `pool.ts` file, update `hasVirtualSupply` and `isLinearPool` to include the new `PoolType`.
```suggestion
Add the Linear Pool to the `PoolType` namespaces within `src/mappings/helpers/pool.ts`. In `pool.ts`, update `hasVirtualSupply` and `isLinearPool` to include the new `PoolType`. 
```

2023-05-19 14:57 UTC, gerrrg commented on docs/guides/boosted-pool-creators/new-protocol.md
> +In `manifest.template.yaml`, copy and paste the `ERC4626LinearPoolV4Factory` entry and change to fit the new linear pool's protocol and version. Verify the events match the source code.
```suggestion
In `manifest.template.yaml`, copy and paste the `ERC4626LinearPoolV4Factory` entry and change to fit the new Linear Pool's protocol and version. Verify the events match the source code. 
```

2023-05-19 14:57 UTC, gerrrg commented on docs/guides/boosted-pool-creators/new-protocol.md
> +Add event handler mappings for the the factory in `poolFactory.ts`. Copy and paste `handleNewERC4626LinearPoolV4` and make necessary changes for the new linear pool's protocol and version. The functi
```suggestion
Add event handler mappings for the factory in `poolFactory.ts`. Copy and paste `handleNewERC4626LinearPoolV4` and make necessary changes for the new Linear Pool's protocol and version. The function name must match the name provided in the factory's handler from `manifest.template.yaml`.
```

2023-05-20 21:31 UTC, gerrrg commented on docs/guides/boosted-pool-creators/new-protocol.md
> +In the `abi` folder add two JSON files: one for the new Linear Pool ABI and one for the the corresponding factory ABI.
```suggestion
In the `abi` folder, add two JSON files: one for the new Linear Pool ABI and one for the the corresponding factory ABI. 
```

2023-05-20 21:32 UTC, gerrrg approved these changes
Looks good now. I added a suggestion to add one comma, but approving now to unblock you

2023-05-20 23:53 UTC, gerrrg approved these changes

2023-05-23 17:19 UTC, mikemcdonald approved these changes

2023-05-23 17:19 UTC, merged