Weights Docs for Managed Pools
balancer/docs pull request #88
Opened 2023-05-24 01:05 UTC by baileyspraggins

2023-05-24 02:15 UTC, gerrrg requested changes
some rephrasings, changed manager to `owner` (the pool itself has no notion of a manager, just a pool owner, which is typically the MPC), recommend adding interfaces for weight updates rather than sending readers to the source code (can keep a reference/link to the file, but definitely add the interfaces), small but important code edit in example

2023-05-24 02:15 UTC, gerrrg commented on docs/concepts/pools/managed.md
> +An important feature of Managed Pools that makes them unique from a standard Weighted Pool is the ability for managers to update token weights. This allows managers to adjust the distributions of ass
```suggestion
An important feature of Managed Pools that makes them distinct from standard Weighted Pools is that they allow the pool `owner` to update token weights. This allows `owner`s to adjust the distributions of assets within a pool, in order to shift to different strategies. An example of this is modifying token weights in response to changes in market conditions.
```

2023-05-24 02:15 UTC, gerrrg commented on docs/concepts/pools/managed.md
> +Updating weights gradually in a linear manner over a set period of time is the recommend method for adjusting token weights. This steady weight update allows token prices to slowly adjust, baiting ar
```suggestion
The recommended technique for updating weights in a Managed Pool is to do so gradually. In a gradual weight update, the pool calculates each weight by linearly interpolating between the start and end weights for the specified time. This steady weight update slowly adjusts token prices, encouraging arbitrageurs to rebalance pool balances in line with the desired weights.
```

2023-05-24 02:15 UTC, gerrrg commented on docs/concepts/pools/managed.md
> +There are pricing risks that liquidity providers are exposed to during weight changes. If token weights are adjusted too quickly before argitragers get a chance to rebalance, prices will have a signi
```suggestion
There are pricing risks that liquidity providers are exposed to during weight changes. If token weights are adjusted too quickly before arbitrageurs get a chance to rebalance, prices will have a significantly negative effect. It is important for `owner`s to allow ample time for the pool to change weights in order to mitigate this risk. This ensures that sufficient time is given for market corrections, reducing potential slippage.
```

2023-05-24 02:15 UTC, gerrrg commented on docs/concepts/pools/managed.md
> +[ManagedPoolSetting.sol](https://github.com/baileyspraggins/balancer-v2-monorepo/blob/master/pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol) provides the necessary logic for viewing and
```suggestion
[ManagedPoolSetting.sol](https://github.com/baileyspraggins/balancer-v2-monorepo/blob/master/pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol) provides the necessary logic for viewing and updating token weights within a Managed Pool. Below are a few basic examples of how an `owner` can interact with token weights on a Managed Pool.
```

2023-05-24 02:15 UTC, gerrrg commented on docs/concepts/pools/managed.md
> +[ManagedPoolSetting.sol](https://github.com/baileyspraggins/balancer-v2-monorepo/blob/master/pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol) provides the necessary logic for viewing and
actually, rather than sending the reader to the file, it might be handy to just copy over the interfaces for the gradual weight update setter/getter

2023-05-24 02:15 UTC, gerrrg commented on docs/concepts/pools/managed.md
> +  _updateWeights(block.timestamp, block.timestamp + _REWEIGHT_DURATION, _poolTokens, newWeights);
this uses a function from a sample that is not copied here -- use the mp gradual weight update call directly

2023-05-31 13:33 UTC, gerrrg requested changes
rephrasing

2023-05-31 13:33 UTC, gerrrg commented on docs/concepts/pools/managed.md
> +There are pricing risks that liquidity providers are exposed to during weight changes. If token weights are adjusted too quickly before arbitrageurs get a chance to rebalance, prices will have a sign
```suggestion
There are pricing risks that liquidity providers are exposed to during weight changes. If token weights are adjusted too quickly, prices can become unfavorable for the pool (and its Liquidity Providers). Arbitrageurs are be able to extract more value when there is a sharper price discrepancy, so it is important for `owner`s to allow ample time for the pool to change weights in order to mitigate this risk. This ensures that sufficient time is given for market/arbitrage corrections, lowering the price impact of the pool rebalancing.
```

2023-06-06 14:17 UTC, gerrrg requested changes

2023-06-06 14:17 UTC, gerrrg commented on docs/concepts/pools/managed.md
> +```
might be nice to add a sample getter for the weight update params as well as the instantaneous weights

https://github.com/balancer/balancer-v2-monorepo/blob/master/pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol#L323-L333

2023-06-22 20:06 UTC, gerrrg requested changes
just one small change now that there is a getter

2023-06-22 20:06 UTC, gerrrg commented on docs/concepts/pools/managed.md
> +[ManagedPoolSetting.sol](https://github.com/balancer/balancer-v2-monorepo/blob/master/pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol) provides the necessary logic for viewing and updatin
```suggestion
[ManagedPoolSetting.sol](https://github.com/balancer/balancer-v2-monorepo/blob/master/pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol) provides the necessary logic for viewing and updating token weights within a Managed Pool. Below are a few basic examples of how to can interact with token weights on a Managed Pool. Only an `owner` can call `updateWeightsGradually` but anyone can call the getter.
```

2023-06-26 17:39 UTC, gerrrg requested changes

2023-06-26 17:39 UTC, gerrrg commented on docs/concepts/pools/managed.md
> +[ManagedPoolSetting.sol](https://github.com/balancer/balancer-v2-monorepo/blob/master/pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol) provides the necessary logic for viewing and updatin
```suggestion
[ManagedPoolSetting.sol](https://github.com/balancer/balancer-v2-monorepo/blob/master/pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol) provides the necessary logic for viewing and updating token weights within a Managed Pool. Only an `owner` can call `updateWeightsGradually`, but anyone can call the getters.
```

2023-06-27 14:17 UTC, gerrrg commented on docs/concepts/pools/managed.md
> +There are pricing risks that liquidity providers are exposed to during weight changes. If token weights are adjusted too quickly, prices can become unfavorable for the pool (and its Liquidity Provide
```suggestion
There are pricing risks that liquidity providers are exposed to during weight changes. If token weights are adjusted too quickly, prices can become unfavorable for the pool (and its Liquidity Providers). Arbitrageurs are able to extract more value when there is a sharper price discrepancy, so it is important for `owner`s to allow ample time for the pool to change weights in order to mitigate this risk. This ensures that sufficient time is given for market/arbitrage corrections, lowering the price impact of the pool rebalancing.
```

2023-06-27 14:33 UTC, gerrrg approved these changes

2023-06-27 15:26 UTC, mikemcdonald approved these changes

2023-06-27 15:26 UTC, merged