Mp pause swaps
balancer/docs pull request #91
Opened 2023-05-24 23:53 UTC by baileyspraggins

Documentation added for pausing and unpausing swaps within Managed Pools

2023-05-31 13:39 UTC, gerrrg requested changes
minor edit to code sample

2023-05-31 13:39 UTC, gerrrg commented on docs/concepts/pools/managed.md
> +```
I would flip these so that `false` is first. Then, after the re-enabling with `true`, you can add a comment about how this may have an instantaneous arbitrage opportunity, and therefore a gradual swap fee update from <high> to <low> can be helpful

2023-06-06 14:13 UTC, gerrrg approved these changes

2023-06-06 14:33 UTC, gerrrg requested changes
Probably worth also adding "how to set circuit breakers" since it may be non-obvious to most users. Would be good to demonstrate querying necessary arguments off-chain (js, ts), calculating values, and passing to a contract.

2023-06-06 14:33 UTC, gerrrg commented on docs/concepts/pools/managed.md
>  uint256 swapFeePercentage = _managedPool.getSwapFeePercentage();
add a sample for getting the gradual swap fee update params

2023-06-06 22:23 UTC, baileyspraggins commented
> Probably worth also adding "how to set circuit breakers" since it may be non-obvious to most users. Would be good to demonstrate querying necessary arguments off-chain (js, ts), calculating values, and passing to a contract.

Maybe we should we add that within the MP circuit breakers docs instead of here. What do you think?

2023-06-22 20:08 UTC, gerrrg requested changes
minor adjustment, then good on my end

2023-06-22 20:08 UTC, gerrrg commented on docs/concepts/pools/managed.md
>  [ManagedPoolSetting.sol](https://github.com/balancer/balancer-v2-monorepo/blob/master/pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol) provides the necessary logic for viewing and updatin
```suggestion
[ManagedPoolSetting.sol](https://github.com/balancer/balancer-v2-monorepo/blob/master/pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol) provides the necessary logic for viewing and updating swap fees within a Managed Pool. Below are a few basic examples of how to interact with swap fees on a Managed Pool. Only an `owner` can set the swap fee parameters, but anyone can call the getter.
```

2023-06-23 18:57 UTC, gerrrg approved these changes

2023-06-24 15:57 UTC, merged